---
  - name: My first playbook
    hosts: ELK
    become: true
    tasks:

            - name: Install docker.io (state=present is optional)
              apt:
                name: docker.io
                state: present
                force_apt_get: yes
                update_cache: yes
            - name: Install python3-pip (state=present is optional)
              apt:
                name: python3-pip
                state: present
            - name: Install docker (state=present is optional)
              pip:
                name: docker
                state: present
            - name: Make sure docker service is running
              systemd:
                name: docker
                enabled: yes